version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_students.sql:/docker-entrypoint-initdb.d/database_students.sql
    ports:
      - "3306:3306"

  pythonapp:
    build: .
    container_name: flask_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "4000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    command: >
      sh -c "sleep 10 && python app.py"  # Espera 10 segundos para asegurar que MySQL esté listo

volumes:
  mysql_data:
